### ISSUE TITLE
Corrigir pequenos erros na seção 6.5.

### ISSUE THREAD

**Issue by arturo32** [pythonfluente/pythonfluente2e#12]
- [x] 6.5.1, legenda do exemplo 13:

> Exemplo 13. Buses haunted by ghost passengers

Deveria estar em inglês mesmo?

- [x]  6.5.1, abaixo do exemplo 13:

> você pode inspecionar o objeto `HauntedBusinit` e ver os estudantes fantasma assombrando o atributo `__defaults__`:

> Por fim, podemos verificar que `bus2.passengers` é um apelido vinculado ao primeiro elemento do atributo `HauntedBus.init.defaults`

Nos dois casos a sintaxe de métodos especiais de Python se confunde com a sintaxe para renderização de palavras em itálico em AsciiDoc. Para contornar isso, basta escrever `HauntedBus.\\__init__` e `HauntedBus.\\__init__.\\__defaults__` no documento.

Obs.: O livro parece não estar atualizado com os últimos commits.

**Comment by arturo32** [comment]
Primeiro ponto é traduzido pelo PR #11 .

**Comment by ramalho** [comment]
Muito grato pelas suas contribuições, @arturo32. Fiz as duas correções. Sobre atualizar o livro a cada push, estou com um problema na github action `publish.yaml`: o login para scp não está funcionando e não sei o que estou fazendo de errado.
