### ISSUE TITLE
GitBook para publicação e gestão do conteúdo

### ISSUE THREAD

**Issue by saymoncoppi** [pythonfluente/pythonfluente2e#15]
Opa!
Durante a live com o Bruno outro dia eu sugeri de vocês usarem uma conta do GitBook para publicar o conteúdo.
Não tenho relação com eles mas o serviço é excelente e seria ótimo term um layout otimizado na publicação.
Como ele permite seções seria uma grande vantagem para a publicação facilitando a leitura, adicionalmente features como tema escuro, poder converter em epub e pdf.

Link dos caras: https://www.gitbook.com

Sou fã do seu trabalho então se sua obra pode ficar mais otimizada para chegar em mais pessoas, seria muito legal poder contribuir!

**Comment by ramalho** [comment]
O gitbook suporta Asciidoc? Se não suporta, não vale a pena.

**Comment by ramalho** [comment]
Agora me interessei! Vou estudar o GitBook. Grato pela dica!

**Comment by ramalho** [comment]
A adoção do GitBook não é uma prioridade. Vou fechar esse issue como "não planejado".
