### ISSUE TITLE
Criar github action para gerar livros em pdf

### ISSUE THREAD

**Issue by mruncleleon** [pythonfluente/pythonfluente2e#17]
Olá pessoal, obrigado pelo incrível trabalho nessa tradução.

Gostaria de sugerir a criação de pdf quando este material for atualizado utilizando o AsciiDoctor-pdf.
Mais informações aqui: https://docs.asciidoctor.org/pdf-converter/latest/convert-to-pdf/#convert-an-asciidoc-document-to-a-pdf

**Comment by mruncleleon** [comment]
Coincidentemente criaram um PR com essa solicitação: https://github.com/pythonfluente/pythonfluente2e/pull/16

**Comment by mruncleleon** [comment]
Coincidentemente criaram um PR com essa solicitação: https://github.com/pythonfluente/pythonfluente2e/pull/16

**Comment by ramongss** [comment]
@mruncleleon, a PR #16 cria um arquivo .epub. Porém, segundo a documentação que você linkou, o processo para criar um .pdf é bem similar. Acredito que se o @ramalho topar a ideia da geração do epub, é fácil de adaptar o gh actions para criar um pdf no mesmo workflow 😃 .
