### ISSUE TITLE
Pequenas correções para: 13.5. Goose Typing

### ISSUE THREAD

**Issue by CaioMizerkowski** [pythonfluente/pythonfluente2e#18]
Não deveria ser _classes bases abstratas_?
> Usamos _classes base abstratas_ (ABCs) para definir interfaces passíveis de checagem explícita de tipo durante a execução

O uso do plural para bases está presente na documentação do python em português, citada logo em seguida no texto. Esse padrão, usando _base_ e não _bases_ está presente durante todo o texto.

---
Falta um ponto ao final de:
> (o sequenciamento de DNA cada vez mais barato e rápido vem tornando a cladística muito prática em muito mais casos)

---
Trocar a virgula por um ponto:
> e especificamente não precisa herdar dela!), Isso é um longo caminho andado

---
Tem um ponto sobrando nesse pedaço:
> tipicamente praticada pela maioria do programadores orientados a .objetos.

---
Não tem ABC demais nesse texto?
> Os métodos concretos em cada ABC de collections.abc ABC são implementados

Na versão em inglês só aparece uma vez: _The concrete methods in each collections.abc ABC are implemented_

---
Ficou um pouco estranho a frase:
> funciona executando uma busca sequencial na sequência

---
Palavra repetida
> mas se _sua_ a sua sequência concreta mantém seus itens e ordenados

---
Pequena correção: _disponível_
> você precisa saber o quê está _dispinível_

---
Talvez trocar por: _Mas as mais usadas estão em collections.abc_
> Mas a maioria das mais usadas estão em collections.abc

---
Figura é feminino: _A_ Figura...
> _O_ [Figura 4](https://pythonfluente.com/#collections_uml) é um diagrama de classe resumido

---
Sobrou um texto em inglês para ser retirado:
> Isso é explicado no box seguinte. The next box explains.

---
Trocar a virgula antes de _Assim_ por um ponto:
> são ferramentas para criar frameworks, Assim, apenas uma pequena minoria

---
Pequeno erro: _escritos_
> O nome da ABC Tombola e de seus métodos abstratos estão _escritoa_ em itálico

**Comment by ramalho** [comment]
Muito grato pelas suas contribuições @CaioMizerkowski!

Fiz quase todas as correções que você indicou. Duas já tinham sido corrigidas por outros colaboradores.

A primeira eu não rejeitei. Infelizmente eu discordo da tradução adotada na documentação do Python. Para mim, o plural de Classe Base Abstrata é Classes Base Abstratas, mas eu posso estar errado.

No entanto, para me convencer do contrário será necessário encontrar uma pessoa muito convincente com argumentos de gramática E que entenda também de programação orientada a objetos...

Aguardando quem possa esclarecer!

**Comment by ramalho** [comment]
Vou fechar o issue enquanto não resolvemos a parada gramatical das Classes Base(s) Abstratas. Reabrirei se aparecerem argumentos convincentes para mudar.
