### ISSUE TITLE
Sugestão de termos em português.

### ISSUE THREAD

**Issue by lrlucena** [pythonfluente/pythonfluente2e#21]
Olá pessoal,

Gostaria de sugerir alguns termos em português para evitar o uso de estrangeirismos.

Segue abaixo uma lista de alguns termos em português que poderiam ser usados em vez de seus equivalentes em inglês:

- [x] **performance** -> desempenho
- [x] **container** -> contêiner
- [x] **query** -> consulta
- [x] **factory** -> fábrica
- [x] **stack** -> pilha

Termos sem um equivalente em português:

- [x] **status** -> _estado ??_
- [x] **aliasing** ->
- [x] **função callback** -> _função de retorno ??_  
- [x] **caching** ->
- [x] **hashable** -> _hasheável ??_
- [x] **deadlock** -> _bloqueio mútuo, impasse ??_

O que vocês acham?

**Comment by pauloc** [comment]
Caro Leonardo,

Eu e o Luciano estamos conversando constantemente sobre que termos traduzir
e que termos deixar em inglês.

Tem uma linha fina aí. Além de palavras sem tradução consagrada ou razoável
(tipo "aliasing"), há a questão do público-alvo. Na área de tecnologia as
pessoas muitas vezes se acostumam a usar o termo em inglês, e traduzir
dificulta o entendimento.
Para mim, por exemplo, seria o caso de "query", que é usada na área de BD
há décadas (apesar de "consulta" ser válida em muitos contextos).

Das suas sugestões (da primeira lista), concordo com contêiner. "Factory"
depende do contexto. Acho que "query" deveria ficar em inglês mesmo.
"Performance" é uma palavra em português.

Na segunda lista, estabilizamos "alias" e "aliasing" (traduzindo entre
parênteses por apelido e apelidamento na primeira ocorrência). Hashable é
intraduzível mesmo, status é bastante usado em português, então é
indiferente - serve para variar o texto.

abs.

Paulo Candido

**Comment by ramalho** [comment]
Muito grato pelas suas sugestões, @lrlucena. Incorporamos a maioria delas em https://github.com/pythonfluente/pythonfluente2e/blob/main/guia-de-estilo.adoc#1-termos-adotados

A terminologia não está 100% padronizada no texto traduzido, mas é melhor esperar o trabalho de tradução terminar para fazer umas buscas gerais e corrigir onde for preciso.

Mas é importante a gente ir registrando os termos adotados para ajudar o @pauloc e reduzir a necessidade de revisão depois.
