### ISSUE TITLE
Corrigir pequenos erros no texto

### ISSUE THREAD

**Issue by arturo32** [pythonfluente/pythonfluente2e#4]
- [x]  Seção 6.3, logo após Exemplo 3: 

> Entretanto, suponha que um impostor — vamos chamá-lo de Dr. Alexander Pedachenko — alegar ser Charles L. Dodgson 

Possível erro de concordância verbal: `alegar` deveria ser `alega`?

- [x]  Seção 6.3, legenda da Figura 2:

> charles and lewis estão vinculados aos mesmo objeto; (...)

Uso da palavra `and` em vez de `e`;   `aos` deveria ser `ao`.

- [x] Seção 6.3.1.:

> Objetos sentinela são outro exemplo de singletons que testamos com is Aqui está uma maneira de criar e testar um objeto sentinela:

Falta ponto final antes de `Aqui está`.

- [x] Seção 6.3.2., Exemplo 5:

> Obtem o ID da lista na posição t1[-1].

Falta acento agudo na palavra `Obtem` (`Obtém`).

- [x] Seção 6.4. : 

> Mas se existirem itens mutaveis, isso pode gerar surpresas desagradáveis.

Falta acento agudo na palavra `mutaveis` (`mutáveis`).

- [x] Seção 6.4.:

> Em Exemplo 6 criamos uma lista contendo outra lista e uma tupla, e então fazemos algums mudanças para ver como isso afeta os objetos referenciados.

Erro na palavra `algums`, deveria ser `algumas`.

- [x] Seção 6.4., dica acima do exemplo 6:

> Mas é uma a ferramenta é fantástica, então vale a pena gastar seu tempo copiando e colando o código.

`Mas é uma a ferramenta é fantástica` está estranho, seria `Mas é uma ferramenta fantástica`?

- [x] Seção 6.4, legenda da Figura 4:

> (...) mas a operação l2[2] += (10, 11) criou yma nova tupla com conteúdo (...)

Erro na palavra `yma` que deveria ser `uma`.

- [x] Seção 6.4.1:

> Para ilustrar o uso de copy() e deepcopy(). Exemplo 8 define uma classe simples, Bus (...)

Uso de de ponto final em vez de vírgula após `deepcopy()`?

- [x] Seção 6.4.1, acima do Exemplo 9:

> Agora, no Exemplo 9 interativo, vamos criar um objeto bus (bus1) e dois clones --uma cópia rasa (bus2) e uma cópia profunda (bus3)—para ver o quê acontece quando bus1 deixa um passageiro.

Falta de espaços entre os travessões.

- [x] Seção 6.4.1, Exemplo 9:

> 4. `bus3` é uma cópia profunda de `bus1`, então seu atributo passengers se refere a outra lista.

Faltou acrescentar o estilo de "código" na palavra `passengers`.

- [x] Seção 6.4.1, legenda do Exemplo 10:

>  (...) ainda assim, deepcopy` consegue copiar a.

Crase solta após a palavra `deepcopy`.

Por enquanto li só até a seção 6.4., posso continuar depois. Fico muito feliz em contribuir nem que seja um pouquinho num projeto tão grandioso como esse! Peço desculpas adiantadas se corrigi algo erroneamente.

**Comment by arturo32** [comment]
Duas perguntas: 

Posso ficar editando aqui se eu encontrar mais erros?

Quem resolve esse tipo de issue é a comunidade como um todo ou é melhor deixar para o autor?

**Comment by ramalho** [comment]
@arturo32 muito grato pelas suas contribuições. Fiz todos os reparos que você indicou.

Sobre travessões, a tradução está bagunçada. Todos os travessões deveriam ser com este caractere `—` (em-dash) e não deve ter espaços antes ou depois. No Mac, eu digito <alt><shift><-> (a tecla com hífen) para obter—não sei como faz no PC ou Windows.
