### ISSUE TITLE
Uma `array` ou um `array`?

### ISSUE THREAD

**Issue by alexdesiqueira** [pythonfluente/pythonfluente2e#40]
Opa galeret,
qual é a forma adotada no livro: uma `array` ou um `array`? Vejo ocorrências dos dois.
Me avisem qual é; posso ajudar com um PR.
Agradeço!

**Comment by ramalho** [comment]
Oi, @alexdesiqueira! Adotei "o array". Veja a lista de termos adotados aqui: 
https://github.com/pythonfluente/pythonfluente2e/blob/main/guia-de-estilo.adoc

Quando adotamos um termo estrangeiro, coloquei o "gênero": s.m. ou s.f.

**Comment by aludmila-gdev** [comment]
Bom dia! 

Gostaria de propor uma reflexão sobre este termo!

Concordo com o Luciano sobre a utilização do substantivo masculino, uma vez que em minha visão, essa seria a concordância adequada.

No entanto, para o termo array, gostaria de sugerir que avaliassem a possibilidade de utilizar a palavra em português `Vetor`. Isso pois acredito que o termo remeta mais fielmente ao que queremos dizer, e também é utilizado para o ensino de programação em algumas instituições.

Abaixo, algumas referências que podem contribuir para a reflexão:

## O que é um Array?
Muito utilizada pelos programadores, array é uma estrutura de dados simples presente na maioria das linguagens de programação. Seu principal objetivo é ser um espaço contínuo na memória para organizar e armazenar uma coleção de elementos.
Assim, essas informações podem ser acessadas rapidamente por meio da indicação do índice da posição pretendida.
> Fonte: [O que é array em programação e para que serve](https://kenzie.com.br/blog/o-que-array/#:~:text=trabalha%20na%20%C3%A1rea.-,Qual%20diferen%C3%A7a%20entre%20vetor%20e%20Array%3F,array%20de%20uma%20%C3%BAnica%20dimens%C3%A3o.)

# Introdução aos vetores em Python
Como estudado no  [texto a respeito do conceito de vetores](https://www.ime.usp.br/~leo/mac2166/2017-1/introducao_vetores_python.html#) , um vetor é uma sequência de dados ocupando posições consecutivas de memória e por isso existe uma ordem natural (o primeiro elemento, o segundo e assim por diante). A grande vantagem de usar vetor é poder trabalhar com um grande número de variáveis utilizando um único nome (para a variável). Para isso existe uma sintaxe especial para pegar elementos do vetor em posições específicas (como o primeiro elemento ou o décimo elemento).
> Fonte: https://www.ime.usp.br/~leo/mac2166/2017-1/introducao_vetores_python.html

**Comment by ramalho** [comment]
@aludmila-gdev muito grato pelas suas considerações.

Vamos ficar com _o array_, para evitar confusão com as classes `Vector` que aparecem em alguns capítulos, e representam vetores matemáticos como sequências de números. Naquele caso é o conceito matemático que importa: a interface e nem tanto a implementação (que é baseada em `array.array`). 

Quando falo de _array_  no livro, o foco é na implementação, na forma de uma sequência de números alocados em um espaço contíguo de memória, como um _array_ em C.

**Comment by villares** [comment]
Achei adequado usar o termo *array* inclusive por conta do que foi explicado pelo Luciano, só queria comentar que se fosse pra traduzir, tem uma tradução tradicional em português, que talvez tenha caído em desuso, é *arranjo*.  E *string* é cadeia de caracteres, mas ninguém quase traduz (e OK).

**Comment by ramalho** [comment]
Já li _arranjo_, mas realmente acho bem pouco usado. Vou ficar com _o array_ mesmo.

**Comment by ramalho** [comment]
Já li _arranjo_, mas realmente acho bem pouco usado. Vou ficar com _o array_ mesmo.

Grato pelas contribuições, pessoal!

**Comment by ramalho** [comment]
Já li _arranjo_, mas realmente acho bem pouco usado. Vou ficar com _o array_ mesmo.

Grato pelas contribuições, pessoal!
