### ISSUE TITLE
Corrigir print -> exibir em alguns lugares

### ISSUE THREAD

**Issue by villares** [pythonfluente/pythonfluente2e#48]
- [x] https://pythonfluente.com/#context_managers_sec
"Imprime uma str, depois o valor [...]" -> 'Exibe uma str, depois o valor [...]"
"Se a exceção não é None e seu tipo é ZeroDivisionError, imprime uma mensagem…​" -> "Se a exceção não é None e seu tipo é ZeroDivisionError, exibe uma mensagem…​"

- [ ] https://pythonfluente.com/#_o_repl
Talvez aqui seja melhor manter imprime mesmo... " (read-eval-print-loop, loop-lê-calcula-imprime)"

- [x] https://pythonfluente.com/#_experimentando_com_executor_map
"Essa função simplesmente imprime quaisquer argumentos [...]" -> ""Essa função simplesmente exibe quaisquer argumentos [...]"

**Comment by ramalho** [comment]
Muito grato pelas contribuições, @villares !

**Comment by villares** [comment]
> Muito grato pelas contribuições, @villares !

Legal!!! Quando puder, confira uma última vez como ficou a frase toda da última correção!
