### ISSUE TITLE
Títulos dos capítulos

### ISSUE THREAD

**Issue by adorilson** [pythonfluente/pythonfluente2e#6]
Há uma inconsistência na capitalização dos capítulos. Em alguns deles, cada palavra começa com maiúscula (como no inglês). Em outras, apenas a primeira letra é maiúscula (como é o certo em português brasileiro).

Caso alguém queira contribuir com isso, o jeito correto já aceito pelos autores é do jeito brasileiro citado acima e de acordo com o [Paulo me respondeu no Twitter](https://twitter.com/paulo_outra_vez/status/1637894433759809554):

```
Sim, nós começamos de um jeito, aí mudamos de ideia no meio do caminho e ainda não voltamos 
para revisar os primeiros. O padrão atual é capitalizar apenas a primeira letra (exceto, claro,
para nomes próprios, tipo "Python").
```

**Comment by ramalho** [comment]
Muito grato por ter levantado essa questão, @adorilson!

Essa mudança é fácil de fazer, mas é mais fácil fazê-la quando a tradução estiver completa.

Vou deixar este issue aberto para não esquecer.

**Comment by ramalho** [comment]
Normalizei todos os títulos de capítulos e seções que encontrei nos capítulos traduzidos antes. A partir de agora, estamos conscientes para manter o padrão, então vou fechar esse issue. Problemas futuros dessa natureza serão pontuais, e serão tratados como as demais correções ortográficas.
