### ISSUE TITLE
Erro de formatação: Seção 2.8.

### ISSUE THREAD

**Issue by luxedo** [pythonfluente/pythonfluente2e#69]
Estou lendo o livro e percebi um pequeno erro no primeiro parágrafo da seção 2.8., no primeiro `+` que deveria aparecer em um bloco de código inline. No entanto, a próxima frase inteira fica como código.

Renderização do site
![image](https://github.com/pythonfluente/pythonfluente2e/assets/14118472/7874424c-c9d5-497b-989e-60140dfd7872)

Visualização no GitHub
![image](https://github.com/pythonfluente/pythonfluente2e/assets/14118472/6a56b43e-2341-4b65-92a1-52f4ca4f3939)

Código fonte
![image](https://github.com/pythonfluente/pythonfluente2e/assets/14118472/2ee7b4a2-9821-4348-b55d-39e255d905c5)

 Aparentemente no `asciidoctor` a notação `` `+``  é usada pra determinar um bloco *inline literal monospace*:
![image](https://github.com/pythonfluente/pythonfluente2e/assets/14118472/24842d40-7123-4776-adaf-f8efbce6ab46)

https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#literals-and-source-code

Seria possível resolver usando um caractere de escape? `` `\+``?

**Comment by luxedo** [comment]
Interessante mencionar que logo abaixo tem uma frase com a mesma sintaxe e a formatação está correta:

![image](https://github.com/pythonfluente/pythonfluente2e/assets/14118472/07eec40e-7c64-4973-bd72-3be071704b60)
![image](https://github.com/pythonfluente/pythonfluente2e/assets/14118472/e6c6b3a8-288f-4b5b-bc01-87e1a4c6d32b)

**Comment by luxedo** [comment]
Apareceram também mais erros no final da seção 2.8.1 e começo da 2.8.2:
![image](https://github.com/pythonfluente/pythonfluente2e/assets/14118472/30b4be75-ff1b-495c-bd80-f8cb023ca490)

**Comment by Ckk3** [comment]
Também encontrei esses erros, criei um PR com as correções.
Obrigado por ter adicionado as informações nesta issue, @luxedo, facilitou muito o desenvolvimento.

**Comment by ramalho** [comment]
Muito grato por reportar, @luxedo, e por consertar, @Ckk3 !
