### ISSUE TITLE
Pequena confusão no último parágrafo do tópico 1.3.1

### ISSUE THREAD

**Issue by ghost** [pythonfluente/pythonfluente2e#74]
TÓPICO 1.3.1: Emulando tipos numéricos

Como está:

"O [Exemplo 2] implementa dois operadores: ` e `*`, para demonstrar o uso básico de `+__add__ e __mul__. No dois casos, ..."

Como deveria ser:

"O [Exemplo 2] implementa dois operadores: `+' e `*`, para demonstrar o uso básico de `__add__ e __mul__. Nos dois casos, ..."

**Comment by ramalho** [comment]
Muito grato por reportar, @ghost. Resolvido.
